name: Build
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!LICENSE'
      - '!README.md'
      - '!CHANGELOG.md'
      - '.github/workflows/build.yml'
  release:
    types: [published]
env:
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/codespaces-nix"
jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          tags: "${{ env.IMAGE_NAME }}:built"
          outputs: type=docker,dest=/tmp/codespaces-nix.tar
          build-args: |
            REVISION=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Store image as artifact
        # if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/codespaces-nix.tar
          retention-days: 1
    permissions:
      contents: read
  push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs:
      - build
    # if: github.event_name == 'release'
    steps:
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: image
      - name: Load image
        run: docker load --input=codespaces-nix.tar
      - id: tag
        name: Tag image
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tag="$(echo "$TAG_NAME" | sed -e 's/^v//')"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          docker tag "${IMAGE_NAME}:built" "${IMAGE_NAME}:${tag}"
      - name: Push image to registry
        env:
          TAG: ${{ steps.tag.outputs.tag }}
        run: docker push "${IMAGE_NAME}:${TAG}"
    permissions:
      packages: write
